{{- if .Values.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "opensearch.uname" . }}-config
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}"
    app: "{{ template "opensearch.uname" . }}"
data:
  {{- range $path, $config := .Values.esConfig }}
  {{ $path }}: |
  {{ $config | indent 4 -}}
  {{- end -}}
  {{- end -}}
